management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
        
billingservice:        
 ribbon:
   eureka: disable
   listOfServers: localhost:8091,localhost:8092
   ServerListRefreshInterval: 2000
   

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
server:
  port: 8090
spring:
  application:
    name: praveen-flipkart-ordermanagement-service
    
praveen-flipkart-ordermanagement-service:
                   billingURL: http://praveen-flipkart-billing-service/rest/billingservice/billingorder
