---
spring:
 application: 
  name: praveen-spring-cloud-config-server

 cloud:
   config:
     server:
       git:
        uri: https://github.com/praveennaga/praveen-spring-config-server-master
        searchPaths: config
server:
 port: 8888

