---
server:
  port: 9411
spring:
  application:
    name: praveen-zipkin-server
security:
   user:
    name: praveen
    password: pcf
    
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost